name: called

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VAR1: ${{ vars.HELLO }}
    steps:
      - run: |
          echo $VAR1