name: Caller

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/called.yml
    with:
      environment: ''

  job2:
    uses: ./.github/workflows/called.yml
    with:
      environment: 'dev'