name: Issue 1445

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/test
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');
            const dir = '${{ github.workspace }}/test'
            if (!fs.existsSync(dir)) {
              fs.mkdirSync(dir);
            }
      - name: Set env to prod
        run: |
          pwd
          echo $GITHUB_ENV
          echo "ENV_NAME=prod" >> $GITHUB_ENV
      - name: Echo ENV_NAME
        run: echo $ENV_NAME
